name: Android develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Copy google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_DEBUG }}
      run: echo $GOOGLE_SERVICES_JSON | base64 --decode --ignore-garbage > ./app/google-services.json

    - name: Copy keystore.properties
      env:
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
      run: echo $KEYSTORE_PROPERTIES > ../keystore.properties

    - name: Copy upload-release.jks
      env:
        KEYSTORE_RELEASE: ${{ secrets.KEYSTORE_UPLOAD_RELEASE }}
      run: echo $KEYSTORE_RELEASE | base64 --decode --ignore-garbage > ../keystore/upload-release.jks

    - name: Copy upload-internal.jks
      env:
        KEYSTORE_RELEASE: ${{ secrets.KEYSTORE_UPLOAD_INTERNAL }}
      run: echo $KEYSTORE_INTERNAL | base64 --decode --ignore-garbage > ../keystore/upload-internal.jks

    - name: Run ktlint
      run: ./gradlew ktlintCheck
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
    
    - name: Build assemble release apk
      run: ./gradlew assembleRelease
