name: Android develop CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Create google-services.json
      env:
        GOOGLE_SERVICES_JSON: ${{ secrets.DEBUG_GOOGLE_SERVICES_JSON }}
      run: echo $GOOGLE_SERVICES_JSON | base64 --decode >> ./app/src/debug/google-services.json
      
    - name: Run ktlint
      run: ./gradlew ktlintCheck
      
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest
    
    - name: Build assemble release apk
      run: ./gradlew assembleRelease
